create or replace PROCEDURE PRC_USER_LOGIN(
    I_USERNAME          IN VARCHAR2,
    I_PASSWORD          IN VARCHAR2,
    O_RESULT            OUT SYS_REFCURSOR,
    O_STATUS_CODE       OUT NUMBER,
    O_STATUS_MESSAGE    OUT VARCHAR2
)
AS
v_count NUMBER;
BEGIN
    SELECT COUNT(1) INTO v_count FROM USERS WHERE USERNAME = I_USERNAME AND PASSWORD = I_PASSWORD;

    OPEN O_RESULT FOR
        SELECT USER_ID, USERNAME--, EMAIL, MOBILE_NO
        FROM USERS
        WHERE USERNAME = I_USERNAME AND PASSWORD = I_PASSWORD;

    IF v_count>0 THEN
        O_STATUS_CODE:= 100;
        O_STATUS_MESSAGE:= 'Login successful.';
    ELSE
        O_STATUS_CODE:= 991;
        O_STATUS_MESSAGE:= 'Invalid credentials.';
    END IF;
END;