SET DEFINE OFF
/
DECLARE
v_count NUMBER ;
BEGIN
    SELECT count(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME='USERS';
    IF v_count=0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE USERS (
        user_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        username VARCHAR2(50) UNIQUE NOT NULL,
        mobile_no VARCHAR2(10) UNIQUE,
        email VARCHAR2(100) UNIQUE NOT NULL,
        password VARCHAR2(255) NOT NULL,
        created_on TIMESTAMP DEFAULT SYSTIMESTAMP,
        modified_on TIMESTAMP DEFAULT SYSTIMESTAMP)';
    END IF;
END;
/
DECLARE
v_count NUMBER ;
BEGIN
    SELECT count(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME='USER_PERMISSIONS';
    IF v_count=0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE USER_PERMISSIONS (
        user_id NUMBER REFERENCES USERS(user_id),
        role VARCHAR2(20) CHECK (role IN (''ADMIN'', ''USER'')),
        PRIMARY KEY (user_id)
        )';
    END IF;
END;
/
DECLARE
v_count NUMBER ;
BEGIN
    SELECT count(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME='GROUPS';
    IF v_count=0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE GROUPS (
        group_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        group_name VARCHAR2(255) NOT NULL,
        created_by_id NUMBER REFERENCES USERS(user_id),
        created_by VARCHAR2(50) NOT NULL,
        created_on TIMESTAMP DEFAULT SYSTIMESTAMP,
        modified_on TIMESTAMP DEFAULT SYSTIMESTAMP
        )';
    END IF;
END;
/
DECLARE
v_count NUMBER ;
BEGIN
    SELECT count(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME='GROUP_MEMBERS';
    IF v_count=0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE GROUP_MEMBERS (
        group_id NUMBER REFERENCES GROUPS(group_id),
        member_id NUMBER REFERENCES USERS(user_id),
        added_on TIMESTAMP DEFAULT SYSTIMESTAMP,
        member_type VARCHAR2(10) DEFAULT ''MEMBER'',
        PRIMARY KEY (group_id, member_id)
        )';
    END IF;
END;
/
DECLARE
v_count NUMBER ;
BEGIN
    SELECT count(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME='EXPENSES';
    IF v_count=0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE EXPENSES (
        expense_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        group_id NUMBER REFERENCES GROUPS(group_id),
        paid_by NUMBER REFERENCES USERS(user_id),
        description VARCHAR2(255),
        amount NUMBER(10,2) NOT NULL,
        created_on TIMESTAMP DEFAULT SYSTIMESTAMP,
        member_ids VARCHAR2(4000) NOT NULL
        )';
    END IF;
END;
/
DECLARE
v_count NUMBER ;
BEGIN
    SELECT count(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME='SPLITS';
    IF v_count=0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE SPLITS (
        split_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        expense_id NUMBER REFERENCES EXPENSES(expense_id),
        user_id NUMBER REFERENCES USERS(user_id),
        amount_owed NUMBER(10,2) NOT NULL,
        status_code NUMBER DEFAULT 1004 CHECK (status_code IN (1004, 1003, 1001, 1000))
        )';
    END IF;
END;
/
DECLARE
v_count NUMBER ;
BEGIN
    SELECT count(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME='SETTLEMENT_REQUESTS';
    IF v_count=0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE SETTLEMENT_REQUESTS (
        request_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        from_user NUMBER REFERENCES USERS(user_id),
        to_user NUMBER REFERENCES USERS(user_id),
        group_id NUMBER REFERENCES GROUPS(group_id),
        amount NUMBER(10,2) NOT NULL,
        status_code NUMBER DEFAULT 1000 CHECK (status_code IN (1000, 1001, 1003)),
        requested_on TIMESTAMP DEFAULT SYSTIMESTAMP,
        modified_on TIMESTAMP
        )';
    END IF;
END;
/
DECLARE
v_count NUMBER ;
BEGIN
    SELECT count(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME='STATUS';
    IF v_count=0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE STATUS (
        status_code NUMBER UNIQUE,
        status_description VARCHAR2(50) UNIQUE
        )';
    END IF;
END;
/
DECLARE
v_count NUMBER ;
BEGIN
    SELECT count(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME='STATUS';
    IF v_count>0 THEN
        EXECUTE IMMEDIATE 'INSERT INTO STATUS (STATUS_CODE,STATUS_DESCRIPTION) VALUES (1000,''REQUESTED'')';
        EXECUTE IMMEDIATE 'INSERT INTO STATUS (STATUS_CODE,STATUS_DESCRIPTION) VALUES (1001,''APPROVED'')';
        EXECUTE IMMEDIATE 'INSERT INTO STATUS (STATUS_CODE,STATUS_DESCRIPTION) VALUES (1003,''REJECTED'')';
        EXECUTE IMMEDIATE 'INSERT INTO STATUS (STATUS_CODE,STATUS_DESCRIPTION) VALUES (1004,''PENDING'')';
    END IF;
END;
/
COMMIT;
