/*create or replace TRIGGER "TRG_CREATE_GROUP" AFTER INSERT ON GROUPS
FOR EACH ROW
    
BEGIN
    IF :NEW.GROUP_ID IS NOT NULL THEN
        INSERT INTO GROUP_MEMBERS (GROUP_ID, MEMBER_ID)
        VALUES (:NEW.GROUP_ID, :NEW.CREATED_BY_ID);
    END IF;
END TRG_ADD_GROUP_OWNER;
*/
create or replace TRIGGER "TRG_GROUP_CREATE" AFTER INSERT ON GROUPS
FOR EACH ROW
    
BEGIN
    IF :NEW.GROUP_ID IS NOT NULL THEN
        INSERT INTO GROUP_MEMBERS (GROUP_ID, MEMBER_ID, MEMBER_TYPE)
        VALUES (:NEW.GROUP_ID, :NEW.CREATED_BY_ID, 'OWNER');
    END IF;
END TRG_GROUP_CREATE;